/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-02-14 03:10:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.io.*;

public final class deposit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title> Welcome to Ebank </title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <!-- Boxicons CDN Link -->\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	 <script> \r\n");
      out.write("		function validate()\r\n");
      out.write("		{ \r\n");
      out.write("			 var username = document.form.username.value;\r\n");
      out.write("			 var amount = document.form.amount.value; \r\n");
      out.write("			 var password = document.form.password.value;\r\n");
      out.write("			 var accountno= document.form.accountno.value;\r\n");
      out.write("			 if (username==null || username==\"\")\r\n");
      out.write("			 { \r\n");
      out.write("			 alert(\"UserName can't be blank\"); \r\n");
      out.write("			 return false; \r\n");
      out.write("			 }\r\n");
      out.write("			 else if (amount==null || amount==\"\")\r\n");
      out.write("			 { \r\n");
      out.write("			 alert(\"amoount can't be blank\"); \r\n");
      out.write("			 return false; \r\n");
      out.write("			 }\r\n");
      out.write("			 else if(password.length<6)\r\n");
      out.write("			 { \r\n");
      out.write("			 alert(\"Password must be at least 6 characters long.\"); \r\n");
      out.write("			 return false; \r\n");
      out.write("			 } \r\n");
      out.write("			 \r\n");
      out.write("		 } \r\n");
      out.write("		</script>\r\n");
      out.write("		   <!-- Font Icon -->\r\n");
      out.write("		<link rel=\"stylesheet\"\r\n");
      out.write("		href=\"fonts/material-icon/css/material-design-iconic-font.min.css\">\r\n");
      out.write("		\r\n");
      out.write("		<!-- Main css -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("   </head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"sidebar\">\r\n");
      out.write("    <div class=\"logo-details\">\r\n");
      out.write("      <i class='bx bxl-c-plus-plus'></i>\r\n");
      out.write("      <span class=\"logo_name\">Ebank</span>\r\n");
      out.write("    </div>\r\n");
      out.write("      <ul class=\"nav-links\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"welcome.jsp\" class=\"active\">\r\n");
      out.write("            <i class='bx bx-grid-alt' ></i>\r\n");
      out.write("            <span class=\"links_name\">Dashboard</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"balfunc.jsp\">\r\n");
      out.write("            <i class='bx bxs-user-account' ></i>\r\n");
      out.write("            <span class=\"links_name\">Account Details</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"transfer.jsp\">\r\n");
      out.write("            <i class='bx bx-transfer' ></i>\r\n");
      out.write("            <span class=\"links_name\">Fund Transfer</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"deposit.jsp\">\r\n");
      out.write("            <i class='bx bx-pie-chart-alt-2' ></i>\r\n");
      out.write("            <span class=\"links_name\">Deposit</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"withdraw.jsp\">\r\n");
      out.write("            <i class='bx bx-coin-stack' ></i>\r\n");
      out.write("            <span class=\"links_name\">WithDraw</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"trank.jsp\">\r\n");
      out.write("            <i class='bx bx-book-alt' ></i>\r\n");
      out.write("            <span class=\"links_name\">Statements</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"cards.jsp\">\r\n");
      out.write("            <i class='bx bx-user' ></i>\r\n");
      out.write("            <span class=\"links_name\">Cards</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("        <li class=\"log_out\">\r\n");
      out.write("          <a href=\"logout.jsp\">\r\n");
      out.write("            <i class='bx bx-log-out'></i>\r\n");
      out.write("            <span class=\"links_name\">Log out</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("    <section class=\"home-section\">\r\n");
      out.write("    <nav>\r\n");
      out.write("      <div class=\"sidebar-button\">\r\n");
      out.write("        <i class='bx bx-menu sidebarBtn'></i>\r\n");
      out.write("        <span class=\"dashboard\">Dashboard</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"profile-details\">\r\n");
      out.write("        <img src=\"images/profile.jpg\" alt=\"\">\r\n");
      out.write("        <span class=\"admin_name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("        <i class='bx bx-chevron-down' ></i>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("	");
 if(session.getAttribute("username")==null){
		response.sendRedirect("Home.html");
	}
	
      out.write("\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("		<!-- Sing in  Form -->\r\n");
      out.write("		<section class=\"Deposit-Form\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"Deposit-Form\">\r\n");
      out.write("				<input type=\"hidden\" id=\"dep\" value=\"");
      out.print( request.getAttribute("dep") );
      out.write("\">\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"Deposit-Form\">\r\n");
      out.write("						&nbsp;<h2 class=\"form-title\">&nbsp;&nbsp;Deposit-Form</h2>\r\n");
      out.write("						<form name=\"form\" action=\"");
      out.print( request.getContextPath());
      out.write("/depos.jsp\" method=\"post\" onsubmit=\"return validate()\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"amount\">&nbsp;<i class=\"zmdi zmdi-money\"></i></label> <input\r\n");
      out.write("									type=\"text\" name=\"amount\" id=\"amount\"\r\n");
      out.write("									placeholder=\"Enter the amount\" />\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"password\"><i class=\"zmdi zmdi-lock\"></i></label> <input\r\n");
      out.write("									type=\"password\" name=\"password\" id=\"password\"\r\n");
      out.write("									placeholder=\"Password\" />\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group form-button\">\r\n");
      out.write("								<input type=\"submit\" name=\"deposit\" id=\"deposit\"\r\n");
      out.write("									class=\"form-submit\" value=\"Deposit\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("  <!-- JS -->\r\n");
      out.write("<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("   let sidebar = document.querySelector(\".sidebar\");\r\n");
      out.write("let sidebarBtn = document.querySelector(\".sidebarBtn\");\r\n");
      out.write("sidebarBtn.onclick = function() {\r\n");
      out.write("  sidebar.classList.toggle(\"active\");\r\n");
      out.write("  if(sidebar.classList.contains(\"active\")){\r\n");
      out.write("  sidebarBtn.classList.replace(\"bx-menu\" ,\"bx-menu-alt-right\");\r\n");
      out.write("}else\r\n");
      out.write("  sidebarBtn.classList.replace(\"bx-menu-alt-right\", \"bx-menu\");\r\n");
      out.write("}\r\n");
      out.write(" </script>\r\n");
      out.write(" <script src=\"http://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"alert/dist/sweetalert.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var status=document.getElementById(\"dep\").value;\r\n");
      out.write("if(status==\"success\"){\r\n");
      out.write("	swal(\"Congrats\",\"Amount Deposited\",\"success\");\r\n");
      out.write("}else if(status==\"failed\"){\r\n");
      out.write("	swal(\"Sorry\",\"Wrong Credentials\",\"error\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
